// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * FindingConfidence
 */
export type FindingConfidence = 'high' | 'medium' | 'low';

/**
 * FindingDisposition
 */
export type FindingDisposition = 'new' | 'existing' | 'fixed';

/**
 * FindingRead
 */
export type FindingRead = {
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Category
     */
    category: string;
    severity: FindingSeverity;
    confidence: FindingConfidence;
    /**
     * Blocking
     */
    blocking: boolean;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Line Start
     */
    line_start: number;
    /**
     * Line End
     */
    line_end?: number | null;
    /**
     * Source Tools
     */
    source_tools: Array<string>;
    /**
     * Rule Id
     */
    rule_id?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Evidence
     */
    evidence: Array<string>;
    /**
     * Impact
     */
    impact: string;
    /**
     * Fix Recommendation
     */
    fix_recommendation: string;
    /**
     * Test Recommendation
     */
    test_recommendation?: string | null;
    /**
     * Fingerprint
     */
    fingerprint: string;
    disposition?: FindingDisposition;
    /**
     * Id
     */
    id: string;
    /**
     * Review Run Id
     */
    review_run_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FindingSeverity
 */
export type FindingSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PaginatedScans
 */
export type PaginatedScans = {
    /**
     * Items
     */
    items: Array<ReviewRunRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * PolicyPutBody
 */
export type PolicyPutBody = {
    /**
     * Content
     */
    content: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * ReviewRunRead
 */
export type ReviewRunRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo
     */
    repo: string;
    run_kind: RunKind;
    /**
     * Pr Number
     */
    pr_number: number | null;
    /**
     * Head Sha
     */
    head_sha: string;
    /**
     * Base Sha
     */
    base_sha: string | null;
    /**
     * Installation Id
     */
    installation_id: number | null;
    /**
     * Attempt
     */
    attempt: number;
    state: ReviewState;
    /**
     * Superseded By
     */
    superseded_by: string | null;
    trigger_event: TriggerEvent | null;
    /**
     * Delivery Id
     */
    delivery_id: string | null;
    /**
     * Classification
     */
    classification: {
        [key: string]: unknown;
    } | null;
    /**
     * Decision
     */
    decision: {
        [key: string]: unknown;
    } | null;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * ReviewState
 */
export type ReviewState = 'pending' | 'classifying' | 'collecting' | 'normalizing' | 'reasoning' | 'deciding' | 'publishing' | 'completed' | 'failed' | 'superseded';

/**
 * RunKind
 */
export type RunKind = 'pr' | 'baseline';

/**
 * ScanDetailResponse
 */
export type ScanDetailResponse = {
    scan: ReviewRunRead;
    /**
     * Findings
     */
    findings: Array<FindingRead>;
};

/**
 * ScanRequest
 *
 * Request body for baseline repository scan (POST /api/scan).
 */
export type ScanRequest = {
    /**
     * Repo
     *
     * Repository in owner/name format
     */
    repo: string;
    /**
     * Installation Id
     *
     * GitHub App installation ID; auto-discovered when omitted
     */
    installation_id?: number | null;
    /**
     * Branch
     *
     * Branch to scan; defaults to the repo default branch
     */
    branch?: string | null;
    /**
     * Ref
     *
     * Exact commit SHA to scan; takes precedence over branch
     */
    ref?: string | null;
    /**
     * Path
     *
     * Local filesystem path to scan (standalone mode, no GitHub required)
     */
    path?: string | null;
};

/**
 * TriggerEvent
 */
export type TriggerEvent = 'opened' | 'synchronize' | 'ready_for_review';

/**
 * TriggerScanBody
 */
export type TriggerScanBody = {
    /**
     * Repo
     */
    repo?: string | null;
    /**
     * Installation Id
     */
    installation_id?: number | null;
    /**
     * Path
     */
    path?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Github Id
     */
    github_id: number | null;
    /**
     * Github Login
     */
    github_login: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Response Ready Ready Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadyReadyGetResponse = ReadyReadyGetResponses[keyof ReadyReadyGetResponses];

export type CreateScanApiScanPostData = {
    body: ScanRequest;
    path?: never;
    query?: never;
    url: '/api/scan';
};

export type CreateScanApiScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScanApiScanPostError = CreateScanApiScanPostErrors[keyof CreateScanApiScanPostErrors];

export type CreateScanApiScanPostResponses = {
    /**
     * Response Create Scan Api Scan Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type CreateScanApiScanPostResponse = CreateScanApiScanPostResponses[keyof CreateScanApiScanPostResponses];

export type GetScanStatusApiScanRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/scan/{run_id}';
};

export type GetScanStatusApiScanRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanStatusApiScanRunIdGetError = GetScanStatusApiScanRunIdGetErrors[keyof GetScanStatusApiScanRunIdGetErrors];

export type GetScanStatusApiScanRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReviewRunRead;
};

export type GetScanStatusApiScanRunIdGetResponse = GetScanStatusApiScanRunIdGetResponses[keyof GetScanStatusApiScanRunIdGetResponses];

export type RegisterApiAuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Response Logout Api Auth Logout Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type LogoutApiAuthLogoutPostResponse = LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type MeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type MeApiAuthMeGetResponse = MeApiAuthMeGetResponses[keyof MeApiAuthMeGetResponses];

export type GithubLoginApiAuthGithubLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/login';
};

export type GithubLoginApiAuthGithubLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubCallbackApiAuthGithubCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/auth/github/callback';
};

export type GithubCallbackApiAuthGithubCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubCallbackApiAuthGithubCallbackGetError = GithubCallbackApiAuthGithubCallbackGetErrors[keyof GithubCallbackApiAuthGithubCallbackGetErrors];

export type GithubCallbackApiAuthGithubCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersApiAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/users/';
};

export type ListUsersApiAdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiAdminUsersGetError = ListUsersApiAdminUsersGetErrors[keyof ListUsersApiAdminUsersGetErrors];

export type ListUsersApiAdminUsersGetResponses = {
    /**
     * Response List Users Api Admin Users  Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type ListUsersApiAdminUsersGetResponse = ListUsersApiAdminUsersGetResponses[keyof ListUsersApiAdminUsersGetResponses];

export type CreateUserApiAdminUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/admin/users/';
};

export type CreateUserApiAdminUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiAdminUsersPostError = CreateUserApiAdminUsersPostErrors[keyof CreateUserApiAdminUsersPostErrors];

export type CreateUserApiAdminUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserApiAdminUsersPostResponse = CreateUserApiAdminUsersPostResponses[keyof CreateUserApiAdminUsersPostResponses];

export type DeactivateUserApiAdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type DeactivateUserApiAdminUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateUserApiAdminUsersUserIdDeleteError = DeactivateUserApiAdminUsersUserIdDeleteErrors[keyof DeactivateUserApiAdminUsersUserIdDeleteErrors];

export type DeactivateUserApiAdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type DeactivateUserApiAdminUsersUserIdDeleteResponse = DeactivateUserApiAdminUsersUserIdDeleteResponses[keyof DeactivateUserApiAdminUsersUserIdDeleteResponses];

export type GetUserApiAdminUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type GetUserApiAdminUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiAdminUsersUserIdGetError = GetUserApiAdminUsersUserIdGetErrors[keyof GetUserApiAdminUsersUserIdGetErrors];

export type GetUserApiAdminUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserApiAdminUsersUserIdGetResponse = GetUserApiAdminUsersUserIdGetResponses[keyof GetUserApiAdminUsersUserIdGetResponses];

export type UpdateUserApiAdminUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type UpdateUserApiAdminUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiAdminUsersUserIdPatchError = UpdateUserApiAdminUsersUserIdPatchErrors[keyof UpdateUserApiAdminUsersUserIdPatchErrors];

export type UpdateUserApiAdminUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserApiAdminUsersUserIdPatchResponse = UpdateUserApiAdminUsersUserIdPatchResponses[keyof UpdateUserApiAdminUsersUserIdPatchResponses];

export type GetSettingsApiAdminSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/settings/';
};

export type GetSettingsApiAdminSettingsGetResponses = {
    /**
     * Response Get Settings Api Admin Settings  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSettingsApiAdminSettingsGetResponse = GetSettingsApiAdminSettingsGetResponses[keyof GetSettingsApiAdminSettingsGetResponses];

export type UpdateSettingsApiAdminSettingsPutData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/admin/settings/';
};

export type UpdateSettingsApiAdminSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingsApiAdminSettingsPutError = UpdateSettingsApiAdminSettingsPutErrors[keyof UpdateSettingsApiAdminSettingsPutErrors];

export type UpdateSettingsApiAdminSettingsPutResponses = {
    /**
     * Response Update Settings Api Admin Settings  Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateSettingsApiAdminSettingsPutResponse = UpdateSettingsApiAdminSettingsPutResponses[keyof UpdateSettingsApiAdminSettingsPutResponses];

export type DeleteSettingApiAdminSettingsKeyDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/admin/settings/{key}';
};

export type DeleteSettingApiAdminSettingsKeyDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSettingApiAdminSettingsKeyDeleteError = DeleteSettingApiAdminSettingsKeyDeleteErrors[keyof DeleteSettingApiAdminSettingsKeyDeleteErrors];

export type DeleteSettingApiAdminSettingsKeyDeleteResponses = {
    /**
     * Response Delete Setting Api Admin Settings  Key  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteSettingApiAdminSettingsKeyDeleteResponse = DeleteSettingApiAdminSettingsKeyDeleteResponses[keyof DeleteSettingApiAdminSettingsKeyDeleteResponses];

export type ListPoliciesApiAdminPoliciesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/policies/';
};

export type ListPoliciesApiAdminPoliciesGetResponses = {
    /**
     * Response List Policies Api Admin Policies  Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListPoliciesApiAdminPoliciesGetResponse = ListPoliciesApiAdminPoliciesGetResponses[keyof ListPoliciesApiAdminPoliciesGetResponses];

export type SeedPoliciesApiAdminPoliciesSeedPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/policies/seed';
};

export type SeedPoliciesApiAdminPoliciesSeedPostResponses = {
    /**
     * Response Seed Policies Api Admin Policies Seed Post
     *
     * Successful Response
     */
    200: {
        [key: string]: Array<string>;
    };
};

export type SeedPoliciesApiAdminPoliciesSeedPostResponse = SeedPoliciesApiAdminPoliciesSeedPostResponses[keyof SeedPoliciesApiAdminPoliciesSeedPostResponses];

export type DeletePolicyApiAdminPoliciesNameDeleteData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/admin/policies/{name}';
};

export type DeletePolicyApiAdminPoliciesNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePolicyApiAdminPoliciesNameDeleteError = DeletePolicyApiAdminPoliciesNameDeleteErrors[keyof DeletePolicyApiAdminPoliciesNameDeleteErrors];

export type DeletePolicyApiAdminPoliciesNameDeleteResponses = {
    /**
     * Response Delete Policy Api Admin Policies  Name  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeletePolicyApiAdminPoliciesNameDeleteResponse = DeletePolicyApiAdminPoliciesNameDeleteResponses[keyof DeletePolicyApiAdminPoliciesNameDeleteResponses];

export type GetPolicyApiAdminPoliciesNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/admin/policies/{name}';
};

export type GetPolicyApiAdminPoliciesNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPolicyApiAdminPoliciesNameGetError = GetPolicyApiAdminPoliciesNameGetErrors[keyof GetPolicyApiAdminPoliciesNameGetErrors];

export type GetPolicyApiAdminPoliciesNameGetResponses = {
    /**
     * Response Get Policy Api Admin Policies  Name  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetPolicyApiAdminPoliciesNameGetResponse = GetPolicyApiAdminPoliciesNameGetResponses[keyof GetPolicyApiAdminPoliciesNameGetResponses];

export type PutPolicyApiAdminPoliciesNamePutData = {
    body: PolicyPutBody;
    headers?: {
        /**
         * If-Match
         */
        'If-Match'?: string | null;
    };
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/admin/policies/{name}';
};

export type PutPolicyApiAdminPoliciesNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutPolicyApiAdminPoliciesNamePutError = PutPolicyApiAdminPoliciesNamePutErrors[keyof PutPolicyApiAdminPoliciesNamePutErrors];

export type PutPolicyApiAdminPoliciesNamePutResponses = {
    /**
     * Response Put Policy Api Admin Policies  Name  Put
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PutPolicyApiAdminPoliciesNamePutResponse = PutPolicyApiAdminPoliciesNamePutResponses[keyof PutPolicyApiAdminPoliciesNamePutResponses];

export type ListScansApiAdminScansGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Repo
         */
        repo?: string | null;
        /**
         * State
         */
        state?: string | null;
        /**
         * Kind
         */
        kind?: string | null;
    };
    url: '/api/admin/scans/';
};

export type ListScansApiAdminScansGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListScansApiAdminScansGetError = ListScansApiAdminScansGetErrors[keyof ListScansApiAdminScansGetErrors];

export type ListScansApiAdminScansGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedScans;
};

export type ListScansApiAdminScansGetResponse = ListScansApiAdminScansGetResponses[keyof ListScansApiAdminScansGetResponses];

export type DeleteScanApiAdminScansScanIdDeleteData = {
    body?: never;
    path: {
        /**
         * Scan Id
         */
        scan_id: string;
    };
    query?: never;
    url: '/api/admin/scans/{scan_id}';
};

export type DeleteScanApiAdminScansScanIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScanApiAdminScansScanIdDeleteError = DeleteScanApiAdminScansScanIdDeleteErrors[keyof DeleteScanApiAdminScansScanIdDeleteErrors];

export type DeleteScanApiAdminScansScanIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ReviewRunRead;
};

export type DeleteScanApiAdminScansScanIdDeleteResponse = DeleteScanApiAdminScansScanIdDeleteResponses[keyof DeleteScanApiAdminScansScanIdDeleteResponses];

export type GetScanApiAdminScansScanIdGetData = {
    body?: never;
    path: {
        /**
         * Scan Id
         */
        scan_id: string;
    };
    query?: never;
    url: '/api/admin/scans/{scan_id}';
};

export type GetScanApiAdminScansScanIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanApiAdminScansScanIdGetError = GetScanApiAdminScansScanIdGetErrors[keyof GetScanApiAdminScansScanIdGetErrors];

export type GetScanApiAdminScansScanIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScanDetailResponse;
};

export type GetScanApiAdminScansScanIdGetResponse = GetScanApiAdminScansScanIdGetResponses[keyof GetScanApiAdminScansScanIdGetResponses];

export type TriggerScanApiAdminScansTriggerPostData = {
    body: TriggerScanBody;
    path?: never;
    query?: never;
    url: '/api/admin/scans/trigger';
};

export type TriggerScanApiAdminScansTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerScanApiAdminScansTriggerPostError = TriggerScanApiAdminScansTriggerPostErrors[keyof TriggerScanApiAdminScansTriggerPostErrors];

export type TriggerScanApiAdminScansTriggerPostResponses = {
    /**
     * Successful Response
     */
    202: ReviewRunRead;
};

export type TriggerScanApiAdminScansTriggerPostResponse = TriggerScanApiAdminScansTriggerPostResponses[keyof TriggerScanApiAdminScansTriggerPostResponses];

export type CancelScanApiAdminScansScanIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Scan Id
         */
        scan_id: string;
    };
    query?: never;
    url: '/api/admin/scans/{scan_id}/cancel';
};

export type CancelScanApiAdminScansScanIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelScanApiAdminScansScanIdCancelPostError = CancelScanApiAdminScansScanIdCancelPostErrors[keyof CancelScanApiAdminScansScanIdCancelPostErrors];

export type CancelScanApiAdminScansScanIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: ReviewRunRead;
};

export type CancelScanApiAdminScansScanIdCancelPostResponse = CancelScanApiAdminScansScanIdCancelPostResponses[keyof CancelScanApiAdminScansScanIdCancelPostResponses];

export type GithubWebhookWebhooksGithubPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks/github';
};

export type GithubWebhookWebhooksGithubPostResponses = {
    /**
     * Response Github Webhook Webhooks Github Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GithubWebhookWebhooksGithubPostResponse = GithubWebhookWebhooksGithubPostResponses[keyof GithubWebhookWebhooksGithubPostResponses];

export type ScanListUiScansGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ui/scans';
};

export type ScanListUiScansGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type ScanListUiScansGetResponse = ScanListUiScansGetResponses[keyof ScanListUiScansGetResponses];

export type ScanDetailUiScansRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/ui/scans/{run_id}';
};

export type ScanDetailUiScansRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanDetailUiScansRunIdGetError = ScanDetailUiScansRunIdGetErrors[keyof ScanDetailUiScansRunIdGetErrors];

export type ScanDetailUiScansRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type ScanDetailUiScansRunIdGetResponse = ScanDetailUiScansRunIdGetResponses[keyof ScanDetailUiScansRunIdGetResponses];
